steps:
  -name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/karabina-maishin/karabina', '.']

  -name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/karabina-maishin/karabina']

  -name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'karabina', '--image', 'gcr.io/karabina-maishin/karabina', '--platform', 'managed', '--region', 'us-central1']