services:
  app:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: karabina
      POSTGRES_PASSWORD: karabina
      POSTGRES_DB: karabina
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
volumes:
  node_modules:
