version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: pnpm dev

volumes:
  node_modules:
